// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test
void test(const char* app_path, const char* pkg_path);
RcppExport SEXP _Rcoreclr_demo_test(SEXP app_pathSEXP, SEXP pkg_pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type app_path(app_pathSEXP);
    Rcpp::traits::input_parameter< const char* >::type pkg_path(pkg_pathSEXP);
    test(app_path, pkg_path);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Rcoreclr_demo_test", (DL_FUNC) &_Rcoreclr_demo_test, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rcoreclr_demo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
