# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(app_path, pkg_path) {
    invisible(.Call('_Rcoreclr_demo_test', PACKAGE = 'Rcoreclr.demo', app_path, pkg_path))
}

